version: "2"
services:
  web:
    image: thinkshake/api
#    build: .
    ports:
      - "5000:5000"
    links:
      - oauth2-server
    environment:
      - NODE_ENV=development
    container_name: thinkshake-api
  oauth2-server:
    image: tomosm/oauth2-server-example
    ports:
      - "5002:3000"
    command: bash -c '/home/oauth2/oauth2-server/vendors/wait-for-it/wait-for-it.sh db:27017; npm start'
    links:
      - db
      - db:mongodb
    environment:
      - NODE_ENV=development
    container_name: oauth2-server
  db:
    image: mongo
    volumes:
      - /data/db:/data/db
    ports:
      - "27017:27017"
    container_name: oauth2-server-mongo
